source "$PANCDIR/utils/alias.sh"
echo "******************************************"
echo "** PAN-Configurator environment is ready"
echo "******************************************"
echo "* Reminder of available alias for quick"
echo "* access from anywhere:"
echo "*"
echo "* pa_rule-edit, pa_address-edit, pa_service-edit"
echo "* pa_upload-config"
echo ""
